### ISSUE TITLE
HTML templates - Joint Applications

### ISSUE THREAD

**Issue by mpneal** [moneyadviceservice/sfs-developer-toolkit#1]
The IDs on the two elements shown below would benefit from being switched on both sfs-data-entry-template.html and sfs-summary-template.html 

```
<!-- Add the class 'checked' to applicable option below -->
<div class="sfs__row">
	<p class="sfs__label">Application:</p>
	<p class="sfs__checkbox" id="is-joint-application__yes">Single</p>
	<p class="sfs__checkbox" id="is-joint-application__no">Joint</p>
</div>
```

**Comment by malcolmwax** [comment]
Thanks for flagging this up, Michael - we'll get these templates updated shortly.

**Comment by malcolmwax** [comment]
Hi - sorry for the delay. We have just pushed an update which resolves this issue. 
Thanks again,
Malcolm
